### PR TITLE
Remove Dask

### PR DESCRIPTION
**Pull request by esclapez**
Remove Dask in favor of a light asyncio-based runner.

- [x] Remove mention of Dask in the doc
- [x] Remove Dask from toml files in examples
- [x] Remove Dask from dependencies

### CODE REVIEW

**Comment by lukasbaldauf** [comment]
This looks very good!

I noticed that the output from the worker.log is also printed to the sim.log file for a test system i ran. I'm not sure if that is an easy fix?

**Comment by dz24** [comment]
> This looks very good!
> 
> I noticed that the output from the worker.log is also printed to the sim.log file for a test system i ran. I'm not sure if that is an easy fix?

Seems like this occurs for python 3.10-3.12, but does not occur when I run from my macbook.

**Comment by dz24** [comment]
Would also be nice to replace all the "dask" sections with "runner", there is still a few (grep -ri --include="*toml" "dask")

**Comment by esclapez** [comment]
> > This looks very good!
> > I noticed that the output from the worker.log is also printed to the sim.log file for a test system i ran. I'm not sure if that is an easy fix?
> 
> Seems like this occurs for python 3.10-3.12, but does not occur when I run from my macbook.

Indeed, I have the same behavior. I'll try to find a fix.

**Comment by esclapez** [comment]
@dz24 In `infretis/tools/pattern.py` there is a "dask_end" entry in the `w_data` dictionary. Should it be kept for backward compatibility or can it be updated to "runner_end" ? I am unsure what this pattern is for.

**Comment by dz24** [comment]
> @dz24 In `infretis/tools/pattern.py` there is a "dask_end" entry in the `w_data` dictionary. Should it be kept for backward compatibility or can it be updated to "runner_end" ? I am unsure what this pattern is for.

I utilized pattern.py to print out the start and end times of various work tasks, at the "dask/infretis/MD" level (Dask tasks sometimes took some seconds to start). You'll may see one of the figures I created from its data at the presentation. In any case, feel free to update to "runner_end", the tool is currently not being used, and we may move it to the "inftools" repo

**Comment by esclapez** [comment]
> This looks very good!
> 
> I noticed that the output from the worker.log is also printed to the sim.log file for a test system i ran. I'm not sure if that is an easy fix?

After some digging, this is due to differences in the practical implementation of `ProcessPoolExecutor` on Linux vs Windows/MacOS. On the former, child processes are `forked` from a specific point in the Python code and executed within the same global scope basically. On the later, a new instance of the Python code is generated for each child.
The issue is then that on Linux the main process and the child processes have the same logger (the root one that you use in every modules) while on Windows/MacOS each child instance has a separate root logger. For now, I have set the main process logger to different one (called "main") and used this one in the `repex` class, which generates most of (all ?) the top level info in `sim.log`. If another class is supposed to log in `sim.log` from the main process, it will be missing. On the tests I've run, it doesn't seem to be the case.
Dask was always generating new instances of Python in the workers, so it was not an issue (I haven't tried Windows actually).

**Comment by lukasbaldauf** [comment]
Thank you for digging into this! It seems to work for me now :rocket: 

I will talk to Daniel when he comes in, so you can probably merge after that when he approves.

I will wrestle a bit with pydocstyle in the meantime.

**Review by dz24 — APPROVED** [review]
LGTM

**Pull request merged**
